version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go2uz-app
    ports:
      - "8080:8080"
    environment:
      DB_IP: db
      DB_NAME: go2uz
      DB_PASSWORD: 1
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: go2uz
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
