services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fitness-app
    ports:
      - "8080:8080"
    environment:
      DB_IP: db
      DB_NAME: fitnessdatabase
      DB_PASSWORD: 1
      DB_PORT: 5432 # Set the correct port for internal communication
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: fitnessdatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:




