#version: '3.8'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: fitness
#    ports:
#      - "8080:8080"
#    environment:
#      DB_IP: db
#      DB_NAME: fitness
#      DB_PASSWORD: 1
#    depends_on:
#      - db
#  db:
#    image: postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_PASSWORD: 1
#      POSTGRES_USER: postgres
#      POSTGRES_DB: fitness
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#volumes:
#  pg_data:
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: fitness
    ports:
      - "5432:5432"

