spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/go2uz_db
    username: go2uz_user
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: coursemanagmentt@gmail.com
    password: rmtdqcbpmqabptsc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none

jwt:
  access-expiry: 86400000  # a day in milliseconds
  refresh-expiry: 604800000  # 7 days in milliseconds
  secret: gjhkoiutrefdsavzbxcnmktjyhretgwedfvbnjkrjyerhsfg
