server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/fitness
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: coursemanagmentt@gmail.com
    password: rmtdqcbpmqabptsc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none



jwt:
  access-expiry: 86400000  # a day in milliseconds
  refresh-expiry: 604800000  # 7 days in milliseconds
  secret: gjhkoiutrefdsavzbxcnmktjyhretgwedfvbnjkrjyerhsfg



